package ew.engine.board;

import ew.engine.cards.CardAttribute;
import ew.engine.cards.CardType;
import ew.engine.cards.effects.Effect;

import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

/** Implemented by CardInstance, CommanderInstance, and ZoneInstance. */
public interface LivingObject {
    LivingObject getSelf();
    boolean equals(Object other);
    int hashCode();
    String toString();

    CardType getCardType();
    CardType getCardTypeInstance();
    String getOriginalName();
    String getNameInstance();
    int getHealthInstance();
    int getHealth();
    SideID getOwner();
    CardAttribute getOriginalAttribute();
    CardAttribute getInstanceAttribute();
    List<CounterType> getCounters();
    boolean hasCounter(CounterType counter);
    boolean hasCounter(List<CounterType> counters);
    List<Effect> getEffects();
    List<EffectInstance> getInstancedEffects();
    int getPriority();
    int getX();
    int getQ();
    int getDeclaredNum();
    int getDeclaredName();
    CardAttribute getDeclaredAttribute();
    Pile getDeclaredPile();
    Direction getDeclaredDirection();
    List<Integer> getDeclaredChoices();
    SideID getController();
    SideID getUser();
    /** The cardID in CardDefinition */
    int getOriginalID();
    int getInstanceID();
    List<TargetInstance> getTarget();
    Position getPosition();
    Effect getPlaceCost();
    EffectInstance getInstancedPlaceCost();
    boolean getCommanderOneVis();
    boolean getCommanderTwoVis();
    boolean isFaceUp();
    boolean isRevealed();
    boolean isShrouded();
    boolean wasShroudedThisTurn();
    boolean isNegated();
    Position getUndisplacementLocation();
    EffectDurationInstance getUndisplacementTime();
    boolean isRode();
    boolean isRider();
    boolean isDestroyed(); // for being destroyed on field
    boolean isExcavated();
    boolean isSearched();
    boolean isOriginallyToken();
    boolean isDecisive();
    boolean isTokenInstance();
    boolean isDecisiveInstance();
    boolean isOccupying();
    List<Integer> getUsedByEffectID();

    void setTypeInstance(CardType newType);
    void setName(String newName);
    void setHealthInstance(int healthInstance);
    void setAttributeInstance(CardAttribute attribute);
    void addCounter(CounterType counter, int amount);
    void removeCounter(CounterType counter, int amount);
    void setPriority(int priority);
    void setPosition(Position newPosition);
    void setController(SideID newController);
    void setUser(SideID newUser);
    void setX(int x);
    void setQ(int q);
    void setDeclaredNum(int d);
    void setDeclaredName(int d);
    void setDeclaredAttribute(CardAttribute d);
    void setDeclaredPile(Pile d);
    void setDeclaredDirection(Direction d);
    void setDeclaredChoices(List<Integer> choices);
    void addEffect(EffectInstance effect);
    void removeEffect(int effectID);
    void resetEffects(AtomicInteger nextEffectIDs);
    void setCommanderOneVis(boolean vis);
    void setCommanderTwoVis(boolean vis);
    void setFaceUp(boolean faceUp);
    void setRevealed(boolean revealed);
    void setShrouded(boolean shrouded);
    void setShroudedThisTurn(boolean shroudedThisTurn);
    void setUndisplacementPosition(Position pos);
    void setUndisplacementTime(EffectDurationInstance time);
    void setNegated(boolean negated);
    void setZoneOccupation(boolean occupies);
    void setExcavated(boolean excavated);
    void setSearched(boolean searched);
    void setRideState(boolean riding, boolean ridden);
    void setDestroyedState(boolean destroyed);
    void addTarget(TargetInstance target);
    void addTarget(List<TargetInstance> target);
    void clearTargets();
    void setDecisiveState(boolean isDecisive);
    void setTokenState(boolean isToken);
    void setUsedByEffectID(List<Integer> usingEffectID);
}
